config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  # associations
  belongs_to :user
  belongs_to :product_type
  has_many :variants, dependent: :destroy

  # validations
  validates :sku, presence: true, uniqueness: true
  validates :title, presence: true

  # validate unique sku for products and variants
  validate :uniqueness_of_sku_for_product_and_variants, on: :create, unless: -> { self.user.nil? }
  validate :similar_options_for_product_variants, on: :create, unless: -> { self.variants.blank? }

  accepts_nested_attributes_for :variants, reject_if: :all_blank, allow_destroy: true

  def uniqueness_of_sku_for_product_and_variants
    variants_skus = variants.map(&:sku)
    variants_skus = variants_skus.concat(sku.split)

    if Product.exists?(sku: variants_skus) || Variant.exists?(sku: variants_skus) ||
      !(variants_skus.count == variants_skus.uniq.count)
      errors.add(:base, I18n.t('product.create.sku_validation_error'))
    end
  end

  def similar_options_for_product_variants
    options = { types: [], values: [] }
    variants.each do |variant|
    variant_options = variant.variant_options
    options[:types] << variant_options.map(&:option_type).sort
      options[:values] << variant_options.map(&:option_values).sort
    end
    unless (options[:types].uniq.count == 1) && (options[:values].uniq.count == options[:values].count)
      errors.add(:base, I18n.t('variant.option.not_similar'))
    end
  end
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  # associations
  has_many :products, dependent: :destroy

  # validations
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # associations
  has_many :products, dependent: :destroy

  # validations
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/ }
end

app/models/variant.rb
class Variant < ApplicationRecord
  # associations
  belongs_to :product
  has_many :variant_options

  # validations
  validates :sku, presence: true, uniqueness: true
  validate :uniqueness_of_options_on_variant, on: :create

  accepts_nested_attributes_for :variant_options, reject_if: :all_blank, allow_destroy: true

  def uniqueness_of_options_on_variant
    option_types = variant_options.map(&:option_type)
    unless option_types.count == option_types.uniq.count
      errors.add(:base, I18n.t('variant.create.duplicate_option'))
    end
  end
end

app/models/variant_option.rb
class VariantOption < ApplicationRecord
  # associations
  belongs_to :variant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: :show

  def index
    @products = current_user.products
  end

  def new
    @product = Product.new
  end

  def show; end

  def create
    @product = current_user.products.new(product_params)
    if @product.save
      flash[:notice] = t('product.create.success')
      redirect_to products_path
    else
      flash[:error] = t('errors.messages.not_saved')
      render :new
    end
  end

  private

  def product_params
    params.require(:product).permit(
      :title, :description, :sku, :product_type_id,
      variants_attributes: [:sku, :price, :quantity, variant_options_attributes: [:id, :_destroy, :option_type, :option_value]]
    )
  end

  def find_product
    @product = Product.find_by(id: params[:id])
    redirect_to products_path unless @product
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SellarChamp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/flash' %>
    <%= render 'partials/header' %>
    <%= yield %>
  </body>
</html>

app/views/partials/_flash.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

app/views/partials/_header.html.erb
<% if current_user %>
  <%= link_to "LogOut", destroy_user_session_path, method: :delete %>
<% end %>

app/views/products/_variant_fields.html.erb
<div class="nested-fields well well-compact">
  <div class="form-inline">
    <%=t('variant.headers.sku')%> <%= f.input :sku, :label => false, :placeholder => 'sku', class: 'form-control' %>
    <%=t('variant.headers.price')%> $ <%= f.input :price, :label => false, :placeholder => '0.0', class: 'form-control' %>
    <%=t('variant.headers.quantity')%> <%= f.input :quantity, :label => false, :placeholder => '10', class: 'form-control' %>
    <%= link_to_remove_association f, data: {:confirm => t('variant.remove')}, class: 'btn btn-default btn-xs' do %>
      <div class="glyphicon glyphicon-remove"> X</div>
    <% end %>
  </div>
  <div class="variant-options">
    <%= f.simple_fields_for :variant_options do |variant_option| %>
      <%= render 'variant_option_fields', :f => variant_option %>
    <% end %>
    <%= link_to_add_association 'add option', f, :variant_options %>
  </div>
</div>

app/views/products/_variant_option_fields.html.erb
<div class="nested-fields">
  <div class="form-inline">
    <b> Option </b>
    <%= f.input :option_type, placeholder: 'size', label: false %>
    <%= f.input :option_value, placeholder: 'value', label: false %>
    <%= link_to_remove_association f, class: 'btn btn-default btn-xs' do %>
      <div class="glyphicon glyphicon-remove">X</div>
    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<h2><%=t('welcome')%></h2>
<%= link_to t('product.create_product'), new_product_path %>


<table class="table table-hover">
  <tr>
    <th><%=t('product.headers.title')%></th>
    <th><%=t('product.headers.description')%></th>
    <th><%=t('product.headers.type')%></th>
    <th><%=t('product.headers.action')%></th>
  </tr>

  <% @products.each do |product| %>
    <tr>
      <td><%= product.title %></td>
      <td><%= product.description %></td>
      <td><%= product.product_type.name %></td>
      <td><%= link_to t('product.details'), product_path(product) %></td>
    </tr>
  <% end %>
</table>

app/views/products/new.html.erb
<h2><%=t('product.create_product')%></h2>
<%= simple_form_for @product do |f| %>
  <%= f.label :product_type_id %>
  <%= f.collection_select :product_type_id, ProductType.all, :id, :name %>
  <%= f.input :title, placeholder: t('product.title') %>
  <%= f.input :sku, placeholder: t('product.sku') %>
  <%= f.input :description, placeholder: t('product.description') %>
    <div class="tab-pane active" id="variants">
      <%= f.simple_fields_for :variants do |variant| %>
        <%= render 'variant_fields', f: variant %>
      <% end %>
      <div class="links">
        <%= link_to_add_association t('variant.add'), f, :variants %>
      </div>
    </div>
  <%= f.button :submit %>
<% end %>

app/views/products/show.html.erb
<%= link_to t('product.all'), products_path %>
<h3><%= @product.title %></h3>

<div class="well well-compact">
  <p>
    <strong><%=t('variant.headers.sku')%>:</strong>
    <%= @product.sku %>
  </p>

  <p>
    <strong><%=t('variant.headers.description')%>:</strong>
    <%= @product.description %>
  </p>

  <p>
    <strong><%=t('variant.headers.type')%>:</strong>
    <%= @product.product_type.name %>
  </p>

  <% if @product.variants.present? %>
    <hr>

    <h3><%=t('variant.title')%></h3>

    <table class="table table-hover">
      <tr>
        <th><%=t('variant.headers.sku')%></th>
        <th><%= t('variant.headers.price')%></th>
        <th><%= t('variant.headers.quantity')%></th>
        <th><%= t('variant.headers.options')%></th>
      </tr>

      <% @product.variants.each do |variant| %>
        <tr>
        <td><%= variant.sku %></td>
        <td><%= variant.price %></td>
        <td><%= variant.quantity %></td>
        <% if variant.variant_options.present? %>
          <td>
            <% variant.variant_options.each do |option| %>
              <strong><%=t('variant.headers.option_type')%>:</strong> <%= option.option_type %>
              <strong><%=t('variant.headers.option_value')%>:</strong> <%= option.option_value %>
              <br>
            <% end %>
          </td>
        <% else %>
          <td>N/A</td>
        <% end %>
        </tr>
      <% end %>
    </table>
  <%end%>
</div>